!function e(t,i,s){function n(o,r){if(!i[o]){if(!t[o]){var d="function"==typeof require&&require;
if(!r&&d)return d(o,!0);if(a)return a(o,!0);throw new Error("Cannot find module '"+o+"'")
}var h=i[o]={exports:{}};t[o][0].call(h.exports,function(e){var i=t[o][1][e];return n(i?i:e)
},h,h.exports,e,t,i,s)}return i[o].exports}for(var a="function"==typeof require&&require,o=0;o<s.length;o++)n(s[o]);
return n}({1:[function(e){var t=e("./lib/dom-utils.js"),i=e("./lib/get-image.js"),s=e("./lib/resize-image.js"),n="caption",a=function(e){this.el=e,this.createPanels(),this.createEditor(),this.setupEvents()
};a.prototype=Object.create(t.prototype),a.prototype.constructor=a,a.prototype.createPanels=function(){this.panel=this.createTag("div",{"class":"miniwyg-panel"},[this.boldButton=this.createTag("span",{"class":"btn-bold"}),this.italicButton=this.createTag("span",{"class":"btn-italic"}),this.h1Button=this.createTag("span",{"class":"btn-h1"}),this.h2Button=this.createTag("span",{"class":"btn-h2"}),this.createTag("div",{"class":"panel-clip"})]),this.embedPanel=this.createTag("div",{"class":"miniwyg-panel"},[this.alignLeftButton=this.createTag("span",{"class":"btn-align-left"}),this.alignCenterButton=this.createTag("span",{"class":"btn-align-center"}),this.removeButton=this.createTag("span",{"class":"btn-remove"}),this.createTag("div",{"class":"panel-clip"})]),document.body.appendChild(this.panel),document.body.appendChild(this.embedPanel)
},a.prototype.panelTransitionEnded=function(e){/\bshow\b/.test(e.target.className)||this.removeClassName(e.target,"display")
},a.prototype.createEditor=function(){this.editor=this.createTag("div",{"class":"editor",contenteditable:"true",spellcheck:"false"}),this.el.value.trim().length&&(this.editor.innerHTML=this.el.value),this.wrapper=this.createTag("div",{"class":"miniwyg"},[this.editor,this.plusButton=this.createTag("div",{"class":"plus-sign fa fa-plus-square-o"}),this.createTag("div",{"class":"bottom"})]),this.editor.style.minHeight=this.el.offsetHeight+"px";
var e=this.findCssRules(".miniwyg .editor > *")[0];this.elementSpacing=parseInt(e.style.marginTop),this.addClassName(this.el,"miniwyg-hidden-textarea"),document.execCommand("defaultParagraphSeparator",!1,"p"),this.el.parentNode.insertBefore(this.wrapper,this.el),this.plusHeight=parseInt(window.getComputedStyle(this.plusButton).height)
},a.prototype.setupEvents=function(){this.editor.addEventListener("keydown",this.handleKeyDown.bind(this)),this.editor.addEventListener("keyup",this.wrapOrphanContents.bind(this)),this.editor.addEventListener("paste",this.pasteData.bind(this)),this.editor.addEventListener("mousemove",this.handleMouseMove.bind(this)),this.editor.addEventListener("mouseup",this.trySelectFigure.bind(this),!0),this.panel.addEventListener("transitionend",this.panelTransitionEnded.bind(this)),this.embedPanel.addEventListener("transitionend",this.panelTransitionEnded.bind(this)),this.plusButton.addEventListener("mousedown",this.handleInsert.bind(this)),this.editor.addEventListener("mouseup",function(e){setTimeout(this.checkSelection.bind(this,e),0)
}.bind(this)),this.editor.addEventListener("keyup",function(e){setTimeout(this.checkSelection.bind(this,e),0)
}.bind(this)),this.boldButton.addEventListener("mousedown",this.applyBold.bind(this)),this.italicButton.addEventListener("mousedown",this.applyItalic.bind(this)),this.h1Button.addEventListener("mousedown",this.applyH1.bind(this)),this.h2Button.addEventListener("mousedown",this.applyH2.bind(this)),this.alignLeftButton.addEventListener("mousedown",this.embedAlignLeft.bind(this)),this.alignCenterButton.addEventListener("mousedown",this.embedAlignCenter.bind(this)),this.removeButton.addEventListener("mousedown",this.embedRemove.bind(this)),document.body.addEventListener("DOMNodeRemoved",this.handleNodeRemoved.bind(this)),document.body.parentNode.addEventListener("mousedown",this.hidePanel.bind(this)),document.body.parentNode.addEventListener("mousemove",this.handleMouseLeave.bind(this));
for(var e=this.collectParents(this.el),t=0;t<e.length;t++)"form"===e[t].tagName.toLowerCase()&&e[t].addEventListener("submit",this.updateTextArea.bind(this))
},a.prototype.applyBold=function(){this.inHeading()||document.execCommand("bold",!1,null)
},a.prototype.applyItalic=function(){document.execCommand("italic",!1,null)},a.prototype.applyH1=function(){this.inHeading()?document.execCommand("formatBlock",!1,"p"):document.execCommand("formatBlock",!1,"h1")
},a.prototype.applyH2=function(){this.inHeading()?document.execCommand("formatBlock",!1,"p"):document.execCommand("formatBlock",!1,"h2")
},a.prototype.embedAlignLeft=function(e){e.stopPropagation(),e.preventDefault(),this.addClassName(this.selectedFigure,"align-left"),this.removeClassName(this.alignCenterButton,"active"),this.addClassName(this.alignLeftButton,"active"),this.showEmbedPanel()
},a.prototype.embedAlignCenter=function(e){e.stopPropagation(),e.preventDefault(),this.removeClassName(this.selectedFigure,"align-left"),this.addClassName(this.alignCenterButton,"active"),this.removeClassName(this.alignLeftButton,"active"),this.showEmbedPanel()
},a.prototype.embedRemove=function(){this.selectedFigure.parentNode.removeChild(this.selectedFigure)
},a.prototype.insertImage=function(e){var t=s(e,700,300),i=this.createTag("figure",{contenteditable:!1},[this.createTag("img",{src:t}),this.createTag("figcaption",{contenteditable:!0},[n])]);
"insert"===this.insertOrder?(this.editor.appendChild(i),this.editor.appendChild(this.createTag("p"))):"before"===this.insertOrder&&this.editor.insertBefore(i,this.insertTarget)
},a.prototype.handleNodeRemoved=function(e){e.target.nodeType===document.ELEMENT_NODE&&"figure"===e.target.tagName.toLowerCase()&&this.hideEmbedPanel()
},a.prototype.handleInsert=function(){i(this.insertImage.bind(this))},a.prototype.handleMouseLeave=function(e){e.target!==this.plusButton&&this.removeClassName(this.plusButton,"show")
},a.prototype.handleKeyDown=function(e){if("figcaption"===e.target.tagName.toLowerCase()&&13===e.keyCode){e.stopPropagation(),e.preventDefault();
var t=e.target.parentNode,i=this.getNextElement(t);i||(i=this.editor.appendChild(this.createTag("p"))),-1!==["p","h1","h2","h3"].indexOf(i.tagName.toLowerCase())&&this.startSelection(i)
}},a.prototype.handleMouseMove=function(e){if(e.stopPropagation(),e.target===this.editor){if(!this.editor.firstChild||this.editor.firstChild.nodeType!==document.ELEMENT_NODE)return void this.removeClassName(this.plusButton,"show");
this.addClassName(this.plusButton,"show");for(var t=null,i=0;i<this.editor.childNodes.length;i++)if(this.editor.childNodes[i].offsetTop>e.layerY){t=this.editor.childNodes[i];
break}var s;t?(s=t.offsetTop,this.insertTarget=t,this.insertOrder="before"):this.editor.lastChild?(s=this.editor.lastChild.offsetTop+this.editor.lastChild.offsetHeight+this.elementSpacing,this.insertTarget=null,this.insertOrder="insert"):(s=this.editor.offsetHeight,this.insertTarget=null,this.insertOrder="insert"),this.plusButton.style.top=s-this.elementSpacing/2-this.plusHeight/2+"px"
}else this.removeClassName(this.plusButton,"show")},a.prototype.updateTextArea=function(){for(;this.editor.lastChild.nodeType==document.ELEMENT_NODE&&"p"===this.editor.lastChild.tagName.toLowerCase()&&""===this.editor.lastChild.innerText.trim();)this.editor.removeChild(this.editor.lastChild);
this.el.value=this.editor.innerHTML},a.prototype.checkSelection=function(){for(var e,t=window.getSelection(),i=t.anchorNode,s=this.collectParents(i),n=0;n<s.length;n++)if(s[n].nodeType===document.ELEMENT_NODE&&"figure"===s[n].tagName.toLowerCase()){e=!0;
break}if(e||t.isCollapsed||!t.toString().trim().length||"Control"===t.type)this.hidePanel();
else{var a=t.getRangeAt(0).getClientRects()[0];this.showPanel(a.top+window.scrollY,a.left+a.width/2)
}var o;for(n=0;n<this.editor.childNodes.length;n++)o=this.editor.childNodes[n],o.nodeType===document.ELEMENT_NODE&&"figure"===o.tagName.toLowerCase()&&(-1===s.indexOf(o)?this.removeClassName(o,"figure-focus"):this.selectFigure(o));
e||this.hideEmbedPanel();var r,d,h,l;for(n=0;n<s.length;n++)s[n].nodeType===document.ELEMENT_NODE&&("b"===s[n].tagName.toLowerCase()&&(r=!0),"i"===s[n].tagName.toLowerCase()&&(d=!0),"h1"===s[n].tagName.toLowerCase()&&(h=!0),"h2"===s[n].tagName.toLowerCase()&&(l=!0));
r?this.addClassName(this.boldButton,"active"):this.removeClassName(this.boldButton,"active"),d?this.addClassName(this.italicButton,"active"):this.removeClassName(this.italicButton,"active"),h?this.addClassName(this.h1Button,"active"):this.removeClassName(this.h1Button,"active"),l?this.addClassName(this.h2Button,"active"):this.removeClassName(this.h2Button,"active")
},a.prototype.showPanel=function(e,t){this.panel.style.top=e+"px",this.panel.style.left=t+"px",this.addClassName(this.panel,"display"),setTimeout(this.addClassName.bind(this,this.panel,"show"),0)
},a.prototype.showEmbedPanel=function(){var e=this.selectedFigure.firstChild,t=e.offsetTop+this.wrapper.offsetTop,i=this.wrapper.offsetLeft+e.offsetLeft+e.offsetWidth/2;
this.embedPanel.style.top=t+"px",this.embedPanel.style.left=i+"px",this.addClassName(this.embedPanel,"display"),setTimeout(this.addClassName.bind(this,this.embedPanel,"show"),0)
},a.prototype.hidePanel=function(){this.removeClassName(this.panel,"show")},a.prototype.hideEmbedPanel=function(){this.removeClassName(this.embedPanel,"show")
},a.prototype.selectFigure=function(e){this.addClassName(e,"figure-focus"),this.selectedFigure=e,/\balign-left\b/.test(this.selectedFigure.className)?(this.addClassName(this.alignLeftButton,"active"),this.removeClassName(this.alignCenterButton,"active")):(this.addClassName(this.alignCenterButton,"active"),this.removeClassName(this.alignLeftButton,"active")),this.showEmbedPanel()
},a.prototype.trySelectFigure=function(e){var t=e.target.tagName&&"img"===e.target.tagName.toLowerCase(),i=this.collectParents(e.target);
this.selectedFigure=null,i.unshift(e.target);for(var s,a,o=0;o<i.length;o++)if(s=i[o],"figure"===s.tagName.toLowerCase()){this.selectFigure(s);
for(var r=0;r<this.editor.childNodes.length;r++)a=this.editor.childNodes[r],a.nodeType===document.ELEMENT_NODE&&"figure"===a.tagName.toLowerCase()&&a!=s&&this.removeClassName(a,"figure-focus");
t&&(this.selectedFigure.lastChild.innerText===n?this.selectNode(this.selectedFigure.lastChild):this.startSelection(this.selectedFigure.lastChild)),e.stopPropagation();
break}this.selectedFigure||this.hideEmbedPanel()},a.prototype.pasteData=function(e){if(e.preventDefault(),e.clipboardData&&e.clipboardData.getData){var t=e.clipboardData.getData("text/plain");
if(t.trim().length){for(var i,s=t.split(/(\r?\n)/g),n=0;n<s.length;n++)if(i=s[n],i.trim().length){var a=i.trim().replace(/(<([^>]+)>)/gi,"");
document.execCommand("InsertParagraph",!1,null),document.execCommand("insertHtml",!1,"<p>"+a+"</p>")
}var o=this.editor.firstChild;o.nodeType===document.ELEMENT_NODE&&"p"===o.tagName.toLowerCase()&&""===o.innerText.trim()&&o.parentNode.removeChild(o)
}}},a.prototype.wrapOrphanContents=function(e){if(this.editor.firstChild||document.execCommand("insertHtml",!1,"<p></p>"),13==e.keyCode)for(var t=0;t<this.editor.childNodes.length;t++)this.editor.childNodes[t].nodeType===document.TEXT_NODE&&this.wrapInto(this.editor.childNodes[t],"p")
},window.Miniwyg=a},{"./lib/dom-utils.js":2,"./lib/get-image.js":3,"./lib/resize-image.js":4}],2:[function(e,t){var i=function(){};
i.prototype.collectParents=function(e,t){void 0===t&&(t=[]);var i=e.parentNode;return i&&i.nodeType===document.ELEMENT_NODE?(t.push(i),this.collectParents(i,t)):t
},i.prototype.inHeading=function(e){void 0===e&&(e=["h1","h2","h3"]);var t=window.getSelection();
if(t&&(t=t.focusNode,t&&(t=t.parentNode)),t){var i=this.collectParents(t);i.unshift(t);
for(var s=0;s<i.length;s++)if(-1!==e.indexOf(i[s].tagName.toLowerCase()))return!0
}return!1},i.prototype.createTag=function(e,t,i){void 0===t&&(t={}),void 0===i&&(i=[]);
var s=document.createElement(e);for(var n in t)s.setAttribute(n,t[n]);for(var a=0;a<i.length;a++)s.appendChild("string"==typeof i[a]?document.createTextNode(i[a]):i[a]);
return s},i.prototype.getNextElement=function(e){var t=e.nextSibling;return t&&t.nodeType===document.ELEMENT_NODE?t:t?this.getNextElement(t):null
},i.prototype.wrapInto=function(e,t){var i=document.createElement(t);e.parentNode.insertBefore(i,e),i.appendChild(e)
},i.prototype.addClassName=function(e,t){var i=e.className.split(/\s+/g);-1===i.indexOf(t)&&i.push(t),e.className=i.join(" ")
},i.prototype.removeClassName=function(e,t){var i=e.className.split(/\s+/g),s=i.indexOf(t);
-1!==s&&i.splice(s,1),e.className=i.join(" ")},i.prototype.startSelection=function(e){var t=window.getSelection(),i=document.createRange();
i.setStart(e,0),i.setEnd(e,0),t.removeAllRanges(),t.addRange(i)},i.prototype.selectNode=function(e){var t=window.getSelection(),i=document.createRange();
i.selectNodeContents(e),t.removeAllRanges(),t.addRange(i)},i.prototype.findCssRules=function(e){for(var t,i=[],s=document.styleSheets.length-1;s>=0;s--)for(var n=(document.styleSheets[s].cssRules||[]).length-1;n>=0;n--)t=document.styleSheets[s].cssRules[n],t.selectorText===e&&i.unshift(t);
return i},t.exports=i},{}],3:[function(e,t){function i(e){var t=document.createElement("input");
t.setAttribute("type","file"),t.setAttribute("accept","image/*"),t.addEventListener("change",function(){if(this.files&&this.files[0]){var t=new FileReader;
t.onload=function(t){var i=document.createElement("img");i.src=t.target.result,i.onload=function(){e(i)
}},t.readAsDataURL(this.files[0])}}),t.click()}t.exports=i},{}],4:[function(e,t){function i(e,t,i,a){n||(s=document.createElement("canvas"),n=s.getContext("2d"));
var o=e.width,r=e.height;return o>r?(o>t&&(r*=t/o,o=t),r>i&&(o*=i/r,r=i)):(r>i&&(o*=i/r,r=i),o>t&&(r*=t/o,o=t)),s.width=o,s.height=r,n.drawImage(e,0,0,o,r),a&&(n.fillStyle="white",n.font="36px Arial",n.fillText(a,10,45)),s.toDataURL("image/jpeg",.85)
}var s=null,n=null;t.exports=i},{}]},{},[1]);